### ISSUE TITLE
Hi, i am also getting this same error. if you got any solution for this, please let me know 

### ISSUE THREAD

**Issue by bibinprathap** [chichoch/testarcgis#1]
A/libc: /usr/local/google/buildbot/src/android/ndk-release-r20/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type std::bad_cast: std::bad_cast" failed

**Comment by chichoch** [comment]
Yeah, i'm stuck on react-native `0.61.5` for now... 
I will update you if I find a solution, please do the same if you find something! :)

**Comment by bibinprathap** [comment]
After upgrading to react-native v0.64.0 , ArcGIS SDK v100.10.0 is working fine on android

**Comment by chichoch** [comment]
@bibinprathap Yep, it works for me as well! Thanks!
